Niko/react native template update
Eppo-exp/eppo-docs pull request #548
Opened 2024-12-10 04:42 UTC by nikomancy

Updating the React Native SDK docs to use the new template for SDK docs.

2024-12-20 22:23 UTC, aarsilv requested changes
Thanks for going over the React Native docs as well! Lots of great changes in here 👏 

I left a bunch of comments but am requesting changes for a few main reasons:
1. We should remove the old React Native section
2. Currently, React Native SDK doesn't support persistent caching; we should remove all references
3. There are some initialization options not yet exposed to React Native SDK that we should remove

2024-12-20 22:23 UTC, aarsilv commented on docs/sdks/client-sdks/react-native/quickstart.mdx
> +    'device': user.device,
seems odd we have `user` here but `getCurrentUser()` above. 

I'd replace `getCurrentUser()` with `user?.id` and make these optionally chained (`user?.xxxxxx`) as well

Also we should be consistent with single or double quotes, probably conform on double quotes

2024-12-20 22:23 UTC, aarsilv commented on docs/sdks/client-sdks/react-native/quickstart.mdx
> +}
We should call this `ControlLandingPage` since it's in our `else` later on.

2024-12-20 22:23 UTC, aarsilv commented on docs/sdks/client-sdks/react-native/quickstart.mdx
> +};
same feedback as above

2024-12-20 22:23 UTC, aarsilv commented on docs/sdks/client-sdks/react-native/quickstart.mdx
> +    return <LandingPageC />
same here `<LandingPageControl>`

2024-12-20 22:23 UTC, aarsilv commented on docs/sdks/client-sdks/react-native/initialization.mdx
> +  apiKey: 'YOUR_SDK_KEY',
same issue as elsewhere, currently we need an assignment logger.
```ts
await init({
  apiKey: 'tx6eTRdJh2MD0KV87FB2aQ1uNMhGpzJmucQRifMtvGE',
  assignmentLogger: { logAssignment: (assignment: IAssignmentEvent)=> console.log('TODO: send to warehouse', assignment) }
})
```

2024-12-20 22:23 UTC, aarsilv commented on docs/sdks/client-sdks/react-native/initialization.mdx
> +const user = getCurrentUser();
I think this example is incomplete; I imagine you'd want the rest of the assignment code example we have elsewhere

2024-12-20 22:23 UTC, aarsilv commented on docs/sdks/client-sdks/react-native/initialization.mdx
> +  defaultValue="Eppo provided"
maybe we should put in parenthesis so it's clear this isn't an actual class. `(Eppo provided)`

2024-12-20 22:23 UTC, aarsilv commented on docs/sdks/client-sdks/react-native/initialization.mdx
> +</ApiOptionRef>
This one is not an option for React SDK

2024-12-20 22:23 UTC, aarsilv commented on docs/sdks/client-sdks/react-native/initialization.mdx
> +</ApiOptionRef>
These two are currently not options for the ReactSDK either

2024-12-20 22:23 UTC, aarsilv commented on docs/sdks/client-sdks/react-native/initialization.mdx
> +</ApiOptionRef>
Configuration caching and offline initialization have not yet been exposed to the React SDK. The latter is in the works in a pre-release version. We should make sure part of launching includes updating the documentation.

2024-12-20 22:23 UTC, aarsilv commented on docs/sdks/client-sdks/react-native/initialization.mdx
> +Basic initialization is great for most use cases, but the SDK provides options that you can use during initialization to customize the behavior of the SDK.
We also have a `baseUrl` option which is where the SDK fetches configurations from. Some customers override this went they proxy configuration requests.

2025-01-16 05:42 UTC, nikomancy commented on docs/sdks/client-sdks/react-native/_category_.json
> +    "label": "React Native",
Removed and redirects for each of the headers in it have been added to analogous sections in the new docs.

2025-01-16 05:43 UTC, nikomancy commented on docs/sdks/client-sdks/react-native/assignment.mdx
> +### Local Storage
Removed.

2025-01-16 05:44 UTC, nikomancy commented on docs/sdks/client-sdks/react-native/intro.mdx
> +    link="https://github.com/Eppo-exp/js-client-sdk"
I actually reversed the link to the github and the link to the client doc reference. This is corrected now.

2025-01-16 05:45 UTC, nikomancy commented on docs/sdks/client-sdks/react-native/intro.mdx
> +    link="https://github.com/Eppo-exp/react-native-sdk"
We do have the API reference docs generated for the generic JS client which, if I understand correctly, is shared between the JS, Node, and React Native SDKs, right? So I figured pointing towards it would be okay and possibly helpful. I can remove this if that is not the case. Let me know what you would prefer.

2025-01-16 05:46 UTC, nikomancy commented on docs/sdks/client-sdks/react-native/intro.mdx
> +These docs are specifically for the Javascript client SDK which runs in the browser. If you are using Node.js, see the [Node.js SDK docs](/sdks/server-sdks/node) and if you are using browser JavaScri
Updated.

2025-01-16 05:47 UTC, nikomancy commented on docs/sdks/client-sdks/react-native/quickstart.mdx
> +await init({apiKey: 'SDK_KEY'});
I've updated it to use this code snippet.

2025-01-16 05:55 UTC, nikomancy commented on docs/sdks/client-sdks/react-native/initialization.mdx
> +const user = getCurrentUser();
Rather than incomplete, I think I may have forgotten to delete that `user = getCurrentUser()` bit because it's mostly relevant when you want to do assignments and this snippet is just showing how to get the instance of the client. 

I'm gonna delete this.

2025-01-16 05:58 UTC, nikomancy commented on docs/sdks/client-sdks/react-native/initialization.mdx
> +Basic initialization is great for most use cases, but the SDK provides options that you can use during initialization to customize the behavior of the SDK.
I've added an ApiOptionReference component for that in the commit I'm about to push. Could you check it and confirm that everything is in order?

2025-01-16 05:58 UTC, nikomancy commented on docs/sdks/client-sdks/react-native/initialization.mdx
> +</ApiOptionRef>
Deleting it now.

2025-01-16 05:58 UTC, nikomancy commented on docs/sdks/client-sdks/react-native/initialization.mdx
> +</ApiOptionRef>
Deleted.

2025-01-16 05:59 UTC, nikomancy commented on docs/sdks/client-sdks/react-native/initialization.mdx
> +</ApiOptionRef>
I've removed this from the current state for the docs, but I've also stashed those docs and we can reapply them when it is time.

2025-01-16 06:02 UTC, nikomancy commented on docs/sdks/client-sdks/react-native/initialization.mdx
> +  defaultValue="Eppo provided"
Done.

2025-01-16 06:03 UTC, nikomancy commented on docs/sdks/client-sdks/react-native/quickstart.mdx
> +import init from "@eppo/react-native-sdk";
Updated.

2025-01-16 06:03 UTC, nikomancy commented on docs/sdks/client-sdks/react-native/quickstart.mdx
> +- **Default Value**: Fallback value if assignment fails or rules don't match
Done.

2025-01-16 06:04 UTC, nikomancy commented on docs/sdks/client-sdks/react-native/quickstart.mdx
> +    'device': user.device,
I've updated it with this approach.

2025-01-16 06:04 UTC, nikomancy commented on docs/sdks/client-sdks/react-native/assignment.mdx
> +Depending on the values you pass to the getAssignment function, the SDK will return different results based on whether the subject details match the assignment rules you set in the Eppo UI.
Done.

2025-01-16 06:04 UTC, nikomancy commented on docs/sdks/client-sdks/react-native/assignment.mdx
> +- Numeric
Added.

2025-01-16 06:06 UTC, nikomancy commented
@aarsilv I think I've hit all of the updates you requested. Let me know if you're cool with me merging.

Last steps for me are to deal with the merge conflicts in the redirect file and possibly rebase if any other conflicts exist. Otherwise, this should be good to go.

2025-01-16 06:10 UTC, nikomancy commented
Looks like no merge conflicts. We're good to merge whenever.

2025-01-17 18:25 UTC, merged