Niko/android to new template
Eppo-exp/eppo-docs pull request #550
Opened 2024-12-16 01:31 UTC by nikomancy

# Split Android SDK Documentation into Multiple Pages

## Changes Made
Restructured single android.md file into multiple focused pages:
- intro.mdx: High-level overview and quick links
- quickstart.mdx: Getting started guide
- initialization.mdx: Detailed initialization options
- assignments.mdx: Comprehensive assignment types and patterns

## Why?
- The goal is to make the learning journey for engineers working with specific SDKs easier. 
- Content is easier to find in the TOC improving navigability.
- Code samples for typed examples have been added for ease of use.
- Boilerplate prose docs have been added to allow engineers to learn about relevant conceptual information along side the code without having to context switch to other parts of the docs.

## Review instructions

- The code samples for typed assignments were inferred from the existing code samples and and the Javascript SDK's parameters. Please check those code samples and confirm that they are actually correct.

2024-12-18 21:36 UTC, felipecsl requested changes

2024-12-18 21:36 UTC, felipecsl commented on docs/sdks/client-sdks/android/quickstart.mdx
> +    implementation 'cloud.eppo:android-sdk:4.0.0'
mind bumping this version to `4.3.3` which is the latest?
```suggestion
    implementation 'cloud.eppo:android-sdk:4.3.3'
```

2024-12-18 21:36 UTC, felipecsl commented on docs/sdks/client-sdks/android/quickstart.mdx
> +First, initialize the SDK with your API key. You'll need to do this early in your application lifecycle, typically in your Application class:
```suggestion
First, initialize the SDK with your API key. You'll need to do this early in your application lifecycle, typically in your `Application` subclass:
```

2024-12-18 21:36 UTC, felipecsl commented on docs/sdks/client-sdks/android/assignments.mdx
> +String subjectKey = getUserId() || "anonymous";
you can't use the `||` operator like this in Java (unlike Javascript).
You have to do instead:
```java
String subjectKey = getUserId() != null ? getUserId() : "anonymous";
```

2025-01-27 05:58 UTC, nikomancy commented on docs/sdks/client-sdks/android/assignments.mdx
> +String subjectKey = getUserId() || "anonymous";
Updated.

2025-01-27 15:58 UTC, felipecsl approved these changes

2025-01-27 15:58 UTC, felipecsl commented on docs/sdks/client-sdks/android/assignments.mdx
> +String subjectKey = getUserId() != null ? getUserId() : "anonymous";Map<String, Object> subjectAttributes = new HashMap<>();
missing newline

2025-01-27 15:58 UTC, felipecsl commented on docs/sdks/client-sdks/android/quickstart.mdx
> +    implementation 'cloud.eppo:android-sdk:4.3.3'
latest version is currently 4.4.0

2025-01-28 05:42 UTC, merged