Adding iOS docs.
Eppo-exp/eppo-docs pull request #551
Opened 2024-12-16 01:33 UTC by nikomancy

# Split iOS SDK Documentation into Multiple Pages

## Changes Made
Restructured single iOS.md file into multiple focused pages:
- intro.mdx: High-level overview and quick links
- quickstart.mdx: Getting started guide
- initialization.mdx: Detailed initialization options
- assignments.mdx: Comprehensive assignment types and patterns

## Why?
- The goal is to make the learning journey for engineers working with specific SDKs easier. 
- Content is easier to find in the TOC improving navigability.
- Code samples for typed examples have been added for ease of use.
- Boilerplate prose docs have been added to allow engineers to learn about relevant conceptual information along side the code without having to context switch to other parts of the docs.

## Review instructions
- Additional typed assignment instructions have been inferred from the existing code samples and the 

## Before merge

- [ ] Update redirects
- [ ] Remove ios.md

2024-12-20 23:47 UTC, leoromanovsky requested changes
Overall lgtm; code samples compile. Please give me a ping when addressed the few ❌ and I'll take another read. Thank you!

2024-12-20 23:47 UTC, leoromanovsky commented on docs/sdks/client-sdks/ios/quickstart.mdx
> +3. Set dependency rule to `Up to Next Minor Version` and select `Add Package`
great call out - this is important for customers to be able to get the latest patches

2024-12-20 23:47 UTC, leoromanovsky commented on docs/sdks/client-sdks/ios/quickstart.mdx
> +[Continue with the rest of the quickstart content...]
?

2024-12-20 23:47 UTC, leoromanovsky commented on docs/sdks/client-sdks/ios/quickstart.mdx
> +title: Quickstart
lgtm ✔️

2024-12-20 23:47 UTC, leoromanovsky commented on docs/sdks/client-sdks/ios/initialization.mdx
> +}
verified in xcode

2024-12-20 23:47 UTC, leoromanovsky commented on docs/sdks/client-sdks/ios/initialization.mdx
> +try EppoClient.initializeOffline(
verified in xcode

2024-12-20 23:47 UTC, leoromanovsky commented on docs/sdks/client-sdks/ios/initialization.mdx
> +  defaultValue="undefined"
empty string for all https://github.com/Eppo-exp/eppo-ios-sdk/blob/main/Sources/eppo/Assignment.swift#L1

2024-12-20 23:47 UTC, leoromanovsky commented on docs/sdks/client-sdks/ios/assignments.mdx
> +The SDK periodically retrieves configuration rules from the Eppo server that define how subjects should be allocated to variants. When you call an assignment function, the SDK evaluates these rules l
No polling in Swift - configuration loaded once on session start and whenever user calls `load()`

2024-12-20 23:47 UTC, leoromanovsky commented on docs/sdks/client-sdks/ios/assignments.mdx
> +}
```suggestion
switch assignment {
case "version-a":
    showVersionA()
case "version-b":
    showVersionB()
default:
    showControl()
}
```

totally correct as-is just a suggestion

2024-12-20 23:47 UTC, leoromanovsky commented on docs/sdks/client-sdks/ios/assignments.mdx
> +```
verified in xcode

2024-12-20 23:47 UTC, leoromanovsky commented on docs/sdks/client-sdks/ios/assignments.mdx
> +```
❌ this API does not current exist in swift

2024-12-20 23:53 UTC, leoromanovsky commented on docs/sdks/client-sdks/ios/quickstart.mdx
> +4. Add to your project's target.
Somewhere in the code examples please show how to import the package:

`import EppoFlagging`

2025-01-30 06:19 UTC, nikomancy commented on docs/sdks/client-sdks/ios/quickstart.mdx
> +[Continue with the rest of the quickstart content...]
Left in a placeholder from generated templates. I've updated it with a section covering experiments and pulled the code sample from the Read Me which should mean it will compile.

2025-01-30 06:20 UTC, nikomancy commented on docs/sdks/client-sdks/ios/initialization.mdx
> +  defaultValue="undefined"
Updated and also updated the subjectAttributes to use more specific syntax instead of Javascript terminology.

2025-01-30 06:27 UTC, nikomancy commented on docs/sdks/client-sdks/ios/assignments.mdx
> +The SDK periodically retrieves configuration rules from the Eppo server that define how subjects should be allocated to variants. When you call an assignment function, the SDK evaluates these rules l
Updated.

2025-01-30 06:28 UTC, nikomancy commented on docs/sdks/client-sdks/ios/assignments.mdx
> +```
Deleted that section.

2025-01-30 06:34 UTC, nikomancy commented on docs/sdks/client-sdks/ios/quickstart.mdx
> +4. Add to your project's target.
Done. Also added it to the two other initialization code samples.

2025-01-30 06:57 UTC, merged