Niko/PHP-Docs-to-new-template
Eppo-exp/eppo-docs pull request #552
Opened 2024-12-16 06:20 UTC by nikomancy

## What

Updated the PHP docs to follow a similar template to the node docs.

## Why?
- The goal is to make the learning journey for engineers working with specific SDKs easier.
- Content is easier to find in the TOC improving navigability.
- Code samples for typed examples have been added for ease of use.
- Boilerplate prose docs have been added to allow engineers to learn about relevant conceptual information along side the code without having to context switch to other parts of the docs.

## Review Instructions
- Due to me not knowing PHP, we are missing code samples for bandits.
- All net new code samples in this are untested and need to be validated by someone who actually knows PHP.

## Todo before merge

- [ ] Add bandit code samples
- [ ] Update redirects
- [ ] Delete php.md file

2024-12-21 00:06 UTC, typotter requested changes
Hi Niko,
Thanks for reorganizing our docs! I know there's a lot (and all written by different people). Big undertaking 💪 

I apologize that the docs you had to start with were out of date. When the PHP SDK was last touched, the updated APIs were captured only in the repository's [README](https://github.com/Eppo-exp/php-sdk/blob/main/README.md) and [EppoClient.php](https://github.com/Eppo-exp/php-sdk/blob/12d4d5558a6a84367ad557cb52b83806798c4c5b/src/EppoClient.php#L380)

I copied over a number of code samples as suggestions you should hopefully be able to just drop in.

2024-12-21 00:06 UTC, typotter commented on docs/sdks/server-sdks/php/initialization.mdx
> +The logger receives these parameters:
See [AssignmentEvent](https://github.com/Eppo-exp/php-sdk/blob/main/src/Logger/AssignmentEvent.php)

2024-12-21 00:06 UTC, typotter commented on docs/sdks/server-sdks/php/assignments.mdx
> +## Assignment Logger Schema
please update to schema in [AssignmentEvent](https://github.com/Eppo-exp/php-sdk/blob/main/src/Logger/AssignmentEvent.php)

2024-12-21 00:06 UTC, typotter commented on docs/sdks/server-sdks/php/assignments.mdx
> +getParsedJSONAssignment(...)
```suggestion
getBooleanAssignment(...)
getNumericAssignment(...)
getIntegerAssignment(...)
getStringAssignment(...)
getJSONAssignment(...)
```

2024-12-21 00:06 UTC, typotter commented on docs/sdks/server-sdks/php/assignments.mdx
> +[Placeholder: Need PHP-specific examples for logging to different services (Segment, Rudderstack, mParticle, Snowplow)]
segment logger example: https://github.com/Eppo-exp/php-sdk/blob/main/README.md#assignment-logger

2025-01-17 19:18 UTC, nikomancy commented on docs/sdks/server-sdks/php/intro.mdx
> +The Eppo PHP SDK allows you to manage feature flags and experiments in your PHP applications.
Updated.

2025-01-21 20:48 UTC, typotter commented
Hey @nikomancy 
Is this ready for another look?

2025-01-24 16:13 UTC, nikomancy commented on docs/sdks/server-sdks/php/quickstart.mdx
> +For experiments, you'll need to implement logging. Here's a basic example:
Updated with the new code samples.

2025-01-28 05:22 UTC, typotter approved these changes
Hi Niko,
Thanks again for improving the docs!

I rounded out the code example tweaks and bandit examples in a stacked PR. Please merge #579 into yours before merging to main

2025-01-28 06:04 UTC, nikomancy commented
Looks like everything is good here. I'm merging this now.

2025-01-28 06:04 UTC, merged