Niko/dotnet new template
Eppo-exp/eppo-docs pull request #554
Opened 2024-12-16 06:31 UTC by nikomancy

## What?
Breaking out the Dotnet docs into the multipage template we use for Javascript.

## Why?
- The goal is to make the learning journey for engineers working with specific SDKs easier.
- Content is easier to find in the TOC improving navigability.
- Code samples for typed examples have been added for ease of use.
- Boilerplate prose docs have been added to allow engineers to learn about relevant conceptual information along side the code without having to context switch to other parts of the docs.

## Todo before merge

- [ ] Update redirects
- [ ] delete dotnet.md

2025-01-06 16:53 UTC, typotter requested changes
Looks great overall.
Mostly just nits. Thanks Niko!

2025-01-06 16:53 UTC, typotter commented on docs/sdks/server-sdks/dotnet/quickstart.mdx
> +The SDK handles all the complexity of feature flag evaluation and experiment assignment locally in your application, with no network calls required after initial setup. This guide will walk you throu
This SDK is primarily a server SDK and will poll for updated configuration every 30sec (configurable), so there are actually continuous network calls.

2025-01-06 16:53 UTC, typotter commented on docs/sdks/server-sdks/dotnet/quickstart.mdx
> +| `GetIntegerAssignment()` | Integer |
Returns a `long`

2025-01-06 16:53 UTC, typotter commented on docs/sdks/server-sdks/dotnet/quickstart.mdx
> +| `GetNumericAssignment()` | Float |
nit: returns a `Double`

2025-01-06 16:53 UTC, typotter commented on docs/sdks/server-sdks/dotnet/quickstart.mdx
> +```csharp
Segment Bandit Logger example here:
https://github.com/Eppo-exp/dot-net-server-sdk?tab=readme-ov-file#assignment-and-bandit-action-logger

2025-01-06 16:53 UTC, typotter commented on docs/sdks/server-sdks/dotnet/quickstart.mdx
> +var actions = new Dictionary<string, IDictionary<string, object?>>()
We have a helper class, `ContextAttributes` which makes this typing a little simpler. Check out
https://github.com/Eppo-exp/dot-net-server-sdk/blob/89f65bb5779a7293beff878534381dcc871b03cd/dot-net-sdk/EppoClient.cs#L334

2025-01-06 16:53 UTC, typotter commented on docs/sdks/server-sdks/dotnet/initialization.mdx
> +<ApiOptionRef
Let's put this option last

2025-01-06 16:53 UTC, typotter commented on docs/sdks/server-sdks/dotnet/initialization.mdx
> +<ApiOptionRef
Also supports setting the polling jitter:
https://github.com/Eppo-exp/dot-net-server-sdk/blob/89f65bb5779a7293beff878534381dcc871b03cd/dot-net-sdk/EppoClientConfig.cs#L38

2025-01-06 16:53 UTC, typotter commented on docs/sdks/server-sdks/dotnet/initialization.mdx
> +<ApiOptionRef
No longer supported

2025-01-06 16:53 UTC, typotter commented on docs/sdks/server-sdks/dotnet/assignments.mdx
> +var subjectAttributes = new IDictionary<string, object>
```suggestion
var subjectAttributes = new Dictionary<string, object>
```

2025-01-06 16:53 UTC, typotter commented on docs/sdks/server-sdks/dotnet/assignments.mdx
> +var subjectAttributes = new IDictionary<string, object>
```suggestion
var subjectAttributes = new Dictionary<string, object>
```

2025-01-06 16:53 UTC, typotter commented on docs/sdks/server-sdks/dotnet/assignments.mdx
> +};
```suggestion
var defaultAssignment = (JObject)(new Dictionary<string, object>
{
    ["hero"] = false,
    ["heroImage"] = "placeholder.png",
    ["heroTitle"] = "Placeholder Hero Title",
    ["heroDescription"] = "Placeholder Hero Description"
});
```

2025-01-06 16:53 UTC, typotter commented on docs/sdks/server-sdks/dotnet/bandits.mdx
> +Bandit flag configuration--including setting up the flag key, status quo variation, bandit variation, and targeting rules--are configured within
I think an emdash is the correct punctuation here
ex: 
`Bandit flag configuration &mdash; including setting up the flag key`

2025-01-06 16:53 UTC, typotter commented on docs/sdks/server-sdks/dotnet/bandits.mdx
> +var actions = new Dictionary<string, IDictionary<string, object?>>()
Again, consider using the `ContextAttributes` class here

2025-01-06 16:53 UTC, typotter commented on docs/sdks/server-sdks/dotnet/bandits.mdx
> +There are several overloads of the `GetBanditAction()` method available:
Can link to the [source code](https://github.com/Eppo-exp/dot-net-server-sdk/blob/89f65bb5779a7293beff878534381dcc871b03cd/dot-net-sdk/EppoClient.cs#L267) for full examples of using the convenient overloads

2025-01-06 16:53 UTC, typotter commented on docs/sdks/server-sdks/dotnet/bandits.mdx
> +Similar to subject context, action contexts can be provided as `IDictionary<string, object?>`--which will then assume anything that is a number is a numeric
emdash here as well
(there are some markdown post-processors which can convert `--` to a proper emdash, which is maybe what you're doing here, but it doesn't look like netlify is doing such post processing)

2025-01-13 03:13 UTC, nikomancy commented on docs/sdks/server-sdks/dotnet/quickstart.mdx
> +The SDK handles all the complexity of feature flag evaluation and experiment assignment locally in your application, with no network calls required after initial setup. This guide will walk you throu
Understood. I think I didn't understand that the only SDKs that really benefit from the offline mode use cases were clients.

2025-01-13 03:24 UTC, nikomancy commented on docs/sdks/server-sdks/dotnet/quickstart.mdx
> +```csharp
Updated.

2025-01-13 03:24 UTC, nikomancy commented on docs/sdks/server-sdks/dotnet/quickstart.mdx
> +| `GetNumericAssignment()` | Float |
Updated.

2025-01-13 03:24 UTC, nikomancy commented on docs/sdks/server-sdks/dotnet/quickstart.mdx
> +| `GetIntegerAssignment()` | Integer |
Updated.

2025-01-13 04:04 UTC, nikomancy commented on docs/sdks/server-sdks/dotnet/quickstart.mdx
> +var actions = new Dictionary<string, IDictionary<string, object?>>()
Alright. I'm updating this code example to be more similar to the example in the SDK's code comments. I'll update the subject and the actions with context attributes. 

@typotter Would it make sense to full docs of the ContextAtrribute as part of the Bandits doc page?

2025-01-13 04:05 UTC, nikomancy commented on docs/sdks/server-sdks/dotnet/initialization.mdx
> +<ApiOptionRef
Deleted.

2025-01-13 04:07 UTC, nikomancy commented on docs/sdks/server-sdks/dotnet/initialization.mdx
> +
@typotter Since the `HttpClient` is no longer supported, I will need to modify this code sample. Could you suggest what I should change here?

2025-01-13 04:14 UTC, nikomancy commented on docs/sdks/server-sdks/dotnet/initialization.mdx
> +<ApiOptionRef
Done.

2025-01-13 04:32 UTC, nikomancy commented on docs/sdks/server-sdks/dotnet/initialization.mdx
> +<ApiOptionRef
Adding that option. Making sure my search-fu is good and I understood all of this:

- Jitter is there to add some randomized additional time onto the polling frequency for reasons that are out of scope to explain in this.
- The default value per the consts file is 5000 ms

2025-01-13 04:36 UTC, nikomancy commented on docs/sdks/server-sdks/dotnet/bandits.mdx
> +Bandit flag configuration--including setting up the flag key, status quo variation, bandit variation, and targeting rules--are configured within
I'll be honest, I think I screwed up formatting an unordered list there somehow. This information works a lot better as an unordered list than as a single sentence.

2025-01-13 04:49 UTC, nikomancy commented on docs/sdks/server-sdks/dotnet/quickstart.mdx
> +var actions = new Dictionary<string, IDictionary<string, object?>>()
Nevermind, it looks like we explain that type there and it's a simple method.

2025-01-13 05:14 UTC, nikomancy commented on docs/sdks/server-sdks/dotnet/bandits.mdx
> +There are several overloads of the `GetBanditAction()` method available:
Good suggestion. Link added.

2025-01-13 05:22 UTC, nikomancy commented on docs/sdks/server-sdks/dotnet/bandits.mdx
> +Similar to subject context, action contexts can be provided as `IDictionary<string, object?>`--which will then assume anything that is a number is a numeric
Yep. In Obsidian, I have an extension that does that and I muscle memoried on it.

I opted to rewrite the sentence again. With some additional time away from these docs, I think most of the places where I tried to em-dash usually indicate a complex sentence that I should just rewrite into a couple simpler sentences, an unordered list, or both.

2025-01-13 05:24 UTC, nikomancy commented on docs/sdks/server-sdks/dotnet/initialization.mdx
> +```
@typotter Since the HttpClient is no longer supported, I will need to modify this code sample. Could you suggest what I should change here?

```csharp
var config = new EppoClientConfig("<SDK_KEY>", new MyAssignmentLogger())
{
    PollingIntervalInMillis = 5000,  // Poll every 5 seconds
    BaseUrl = "https://my-custom-endpoint.com/api",
    HttpClient = new HttpClient 
    { 
        Timeout = TimeSpan.FromSeconds(10) 
    }
};

var eppoClient = EppoClient.Init(config);
```

2025-01-17 18:53 UTC, merged

2025-01-20 04:40 UTC, typotter commented on docs/sdks/server-sdks/dotnet/initialization.mdx
> +<ApiOptionRef
correct

2025-01-20 04:40 UTC, typotter commented on docs/sdks/server-sdks/dotnet/initialization.mdx
> +```
The client config code is super simple in its most basic form

`var eppoClientConfig = new EppoClientConfig('SDK-KEY-FROM-DASHBOARD');`

2025-01-20 04:40 UTC, typotter commented on docs/sdks/server-sdks/dotnet/initialization.mdx
> +};
💪